import playwright from '../../desktop/node_modules/@playwright/test/index.js';
import { resolve } from 'node:path';
const { test, expect } = playwright;

test('real WASM adds object volumes from primitives and the browser file picker', async ({ page }) => {
  await page.goto('/');
  await expect(page.getByTestId('slicer-status')).toHaveText('Ready', { timeout: 120_000 });
  await page.locator('#app-tab-prepare').click();
  await page.getByTestId('preset-select').click();
  await page.getByRole('option', { name: 'Bambu Lab P1P 0.4 nozzle', exact: true }).click();
  const cube = resolve(import.meta.dirname, '../../../packages/slicer-wasm/fixtures/cube.stl');
  const chooser = page.waitForEvent('filechooser');
  await page.getByTestId('btn-add-model').click();
  await (await chooser).setFiles(cube);
  await expect(page.getByTestId('btn-slice')).toBeEnabled({ timeout: 30_000 });
  await page.getByTestId('config-mode-scoped').click();
  const list = page.getByTestId('object-list');
  const rows = list.locator('section[data-testid^="plate-group-"] > div[data-testid^="object-"]');
  await expect(rows).toHaveCount(1);
  const button = rows.first().getByRole('button').first();
  await button.click({ button: 'right' });
  await page.getByTestId('objectlist-add-negative_volume').click();
  await page.getByTestId('objectlist-add-negative_volume-Sphere').click();
  const expand = list.locator('[data-testid^="object-expand-"]').first();
  await expect(expand).toBeVisible();
  await expand.click();
  const added = list.locator('[data-testid^="part-"]').filter({ hasText: 'Generic-Sphere' });
  await expect(added).toBeVisible();
  await expect(rows).toHaveCount(1);
  await added.click({ button: 'right' });
  await expect(page.getByTestId('objectlist-add-model_part')).toHaveCount(0);
  await expect(page.getByTestId('objectlist-change-filament')).toHaveCount(0);
  await page.keyboard.press('Escape');
  await page.getByTestId('history-undo').click();
  await expect(list).not.toContainText('Generic-Sphere');
  await page.getByTestId('history-redo').click();
  await expect(list).toContainText('Generic-Sphere');
  await button.click({ button: 'right' });
  await page.getByTestId('objectlist-add-parameter_modifier').click();
  const partChooser = page.waitForEvent('filechooser');
  await page.getByTestId('objectlist-add-parameter_modifier-load').click();
  await (await partChooser).setFiles(cube);
  await expect(list.locator('[data-testid^="part-"]')).toHaveCount(3);
  await expect(rows).toHaveCount(1);
  await page.screenshot({ path: test.info().outputPath('added-volumes.png') });
});
