import playwright from '../../desktop/node_modules/@playwright/test/index.js';
const { test, expect } = playwright;

test('native printer grouping and nozzle variants preserve canonical history and startup selection', async ({ page }, testInfo) => {
  await page.goto('/');
  await expect(page.getByTestId('slicer-status')).toHaveText('Ready', { timeout: 120_000 });
  await page.locator('#app-tab-prepare').click();
  const filament = page.getByTestId('filament-preset-1');
  await expect(filament).toHaveText('Generic PLA');
  await expect(filament).toHaveAttribute('title', 'Generic PLA @System');
  await filament.click();
  const filamentPopup = page.getByRole('menu', { name: 'Filament preset for slot 1', exact: true });
  const filamentSearch = filamentPopup.getByPlaceholder('Search compatible presets…');
  await filamentSearch.fill('Generic PLA');
  await expect(filamentPopup.getByRole('menuitemradio')).toHaveCount(0);
  await filamentSearch.press('ArrowDown');
  await expect(filamentPopup.getByRole('menuitem', { name: 'Generic', exact: true })).toBeFocused();
  await page.keyboard.press('ArrowRight');
  await expect(page.getByRole('menu', { name: 'Generic', exact: true })).toBeVisible();
  await page.keyboard.press('ArrowLeft');
  await expect(page.getByRole('menu', { name: 'Generic', exact: true })).toBeHidden();
  await expect(filamentPopup).toBeVisible();
  await filamentPopup.getByRole('menuitem', { name: 'Generic', exact: true }).hover();
  const genericGroup = page.getByRole('menu', { name: 'Generic', exact: true });
  const systemPla = genericGroup.getByRole('menuitemradio').and(page.getByTitle('Generic PLA @System', { exact: true }));
  await expect(systemPla).toHaveText('Generic PLA');
  await expect(genericGroup).toContainText('Generic PLA');
  await expect(systemPla).toBeVisible();
  await page.screenshot({ path: testInfo.outputPath('filament-vendor-submenu.png') });
  await systemPla.click();
  await expect(filamentPopup).toBeHidden();
  await expect(filament).toBeFocused();
  const printer = page.getByTestId('preset-select');
  await printer.click();
  const popup = page.locator('[data-slot="combobox-content"]');
  await popup.getByPlaceholder('Search presets…').fill('Snapmaker U1');
  await expect(popup.getByRole('option')).toHaveCount(1);
  await popup.getByRole('option', { name: 'Snapmaker U1', exact: true }).click();
  const nozzle = page.getByTestId('nozzle-variant-select');
  await expect(nozzle).toBeEnabled();
  await nozzle.click();
  expect(await page.getByRole('option').allTextContents()).toEqual(['0.2', '0.4', '0.4+0.6', '0.6', '0.8']);
  await page.getByRole('option', { name: '0.4', exact: true }).click();
  await expect(nozzle).toBeEnabled();
  await nozzle.click();
  await page.getByRole('option', { name: '0.6', exact: true }).click();
  await expect(nozzle).toContainText('0.6');
  await expect(nozzle).toBeEnabled();
  await expect(printer).toContainText('Snapmaker U1');
  await expect(printer).toHaveAttribute('title', 'Snapmaker U1 (0.6 nozzle)');
  await page.getByTestId('preset-edit-printer').click();
  await expect(page.getByRole('dialog')).toContainText('Snapmaker U1 (0.6 nozzle)');
  await page.keyboard.press('Escape');
  await page.getByTestId('history-undo').click();
  await expect(nozzle).toContainText('0.4');
  await expect(printer).toHaveAttribute('title', 'Snapmaker U1 (0.4 nozzle)');
  await page.getByTestId('history-redo').click();
  await expect(nozzle).toContainText('0.6');
  await expect(printer).toHaveAttribute('title', 'Snapmaker U1 (0.6 nozzle)');
  const beforeSync = await page.getByTestId('history-undo').getAttribute('title');
  await page.getByTestId('nozzle-sync-placeholder').click();
  expect(await page.getByTestId('history-undo').getAttribute('title')).toBe(beforeSync);
  const row = (await page.getByTestId('printer-nozzle-row').boundingBox())!;
  const button = (await page.getByTestId('nozzle-sync-placeholder').boundingBox())!;
  const trigger = (await nozzle.boundingBox())!;
  expect(trigger.x).toBeGreaterThanOrEqual(button.x + button.width);
  expect(trigger.x + trigger.width).toBeLessThanOrEqual(row.x + row.width + 1);
  expect(await nozzle.locator('.sidebar-dropdown-arrow').count()).toBe(1);
  await page.screenshot({ path: testInfo.outputPath('printer-nozzle.png') });
  await page.reload();
  await expect(page.getByTestId('slicer-status')).toHaveText('Ready', { timeout: 120_000 });
  await page.locator('#app-tab-prepare').click();
  await expect(printer).toContainText('Snapmaker U1');
  await expect(nozzle).toContainText('0.6');
});

test('real bed selector uses native labels, global/local scope, keyboard and compact row layout', async ({ page }, testInfo) => {
  const pageErrors: string[] = [];
  page.on('pageerror', error => pageErrors.push(error.message));
  await page.goto('/');
  await expect(page.getByTestId('slicer-status')).toHaveText('Ready', { timeout: 120_000 });
  const fallback = page.getByRole('button', { name: 'Dismiss serial fallback notice' });
  if (await fallback.isVisible()) await fallback.click();
  await page.locator('#app-tab-prepare').click();
  const printer = page.getByTestId('preset-select');
  await printer.click();
  const popup = page.locator('[data-slot="combobox-content"]');
  await popup.getByPlaceholder('Search presets…').fill('Snapmaker U1');
  const u1 = popup.getByRole('option', { name: 'Snapmaker U1', exact: true });
  const name = await u1.innerText();
  await u1.click();
  await expect(printer).toContainText(name);
  await expect(printer).toBeEnabled();
  const nozzle = page.getByTestId('nozzle-variant-select');
  if ((await nozzle.locator('[data-slot="select-value"]').innerText()).trim() !== '0.4') {
    await nozzle.click();
    await page.getByRole('option', { name: '0.4', exact: true }).click();
    await expect(nozzle).toBeEnabled();
  }
  const global = page.getByTestId('global-bed-type-select');
  await expect(global).toContainText('Textured PEI Plate');
  await expect(global).toBeEnabled();
  expect(await global.getAttribute('title')).toContain('plates without a local override inherit');
  await global.focus(); await global.press('Space');
  const globalPopup = page.locator('[data-slot="select-content"][data-open]');
  await expect(globalPopup).toBeVisible();
  const labels = await globalPopup.getByRole('option').allTextContents();
  expect(labels).toContain('Smooth High Temp Plate');
  expect(labels).not.toContain('High Temp Plate');
  const last = labels.at(-1)!;
  await page.keyboard.press('End'); await page.keyboard.press('Enter');
  await expect(global).toContainText(last); await expect(global).toBeEnabled();
  await expect(page.getByTestId('history-undo')).toBeEnabled();
  await page.getByTestId('history-undo').click();
  await expect(global).toContainText('Textured PEI Plate');
  await page.getByTestId('history-redo').click();
  await expect(global).toContainText(last);
  await page.getByTestId('config-mode-plates').click();
  const local = page.getByTestId('config-input-curr_bed_type');
  await expect(local).toContainText(last);
  await local.click();
  const localPopup = page.locator('[data-slot="select-content"][data-open]');
  await expect(localPopup).toBeVisible();
  expect(await localPopup.getByRole('option').allTextContents()).toEqual(labels);
  await localPopup.getByRole('option', { name: 'Engineering Plate', exact: true }).click();
  await expect(local).toContainText('Engineering Plate');
  await expect(global).toContainText(last);
  await local.hover(); await expect(page.locator('[data-slot="tooltip-content"][data-open]')).toContainText('source: Plate');
  await page.getByTestId('config-reset-curr_bed_type').click();
  await expect(local).toContainText(last);
  await local.hover(); await expect(page.locator('[data-slot="tooltip-content"][data-open]')).toContainText('source: Project');
  await page.mouse.move(900, 500);
  await expect(page.locator('[data-slot="tooltip-content"]')).toHaveCount(0);
  const checkRow = async () => {
    const left = (await printer.boundingBox())!, right = (await global.boundingBox())!, row = (await page.getByTestId('printer-bed-row').boundingBox())!;
    expect(right.x).toBeGreaterThanOrEqual(left.x + left.width);
    expect(Math.abs(right.y - left.y)).toBeLessThan(2);
    expect(right.x + right.width).toBeLessThanOrEqual(row.x + row.width + 1);
    expect(right.width).toBeGreaterThan(40);
    expect(await global.locator('.sidebar-dropdown-arrow').count()).toBe(1);
  };
  await checkRow();
  await page.screenshot({ path: testInfo.outputPath('plate-bed-rendered.png') });
  const resizer = page.getByTestId('sidebar-resizer'); await resizer.focus();
  for (let i = 0; i < 16; i++) await resizer.press('ArrowLeft');
  await checkRow();
  const value = global.locator('[data-slot="select-value"]');
  expect(await value.evaluate(element => getComputedStyle(element).textOverflow)).toBe('ellipsis');
  expect(await global.getAttribute('title')).toContain(last);
  await page.screenshot({ path: testInfo.outputPath('plate-bed-narrow.png') });
  const canvas = (await page.getByTestId('viewport').locator('canvas[data-engine^="three.js"]').boundingBox())!;
  await page.mouse.click(canvas.x + canvas.width - 40, canvas.y + 80, { button: 'right' });
  await page.getByTestId('btn-add-primitive').click();
  await page.getByTestId('btn-add-cube').click();
  await expect(page.getByTestId('btn-slice')).toBeEnabled({ timeout: 30_000 });
  await page.getByTestId('btn-slice').click();
  await expect(page.getByTestId('slicer-status')).toHaveText('Sliced', { timeout: 60_000 });
  await expect(page.getByTestId('btn-export')).toBeEnabled({ timeout: 30_000 });
  await page.reload();
  await expect(page.getByTestId('slicer-status')).toHaveText('Ready', { timeout: 120_000 });
  await page.locator('#app-tab-prepare').click();
  await expect(global).toContainText(last);
  expect(pageErrors).toEqual([]);
});
